version: "3.7"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: shailensukul/pi-mvcapp:1.0.0.1
    deploy:
      placement:
        constraints: [node.role == manager]     
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    #network_mode: host
    #networks:
    #  - webnet
  redis:
    image: redis
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - "/home/redis/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    command: redis-server --appendonly yes --maxmemory 512mb --tcp-backlog 128
    #network_mode: host
    #networks:
    #  - webnet
  visualizer:
    image: alexellis2/visualizer-arm
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    #network_mode: "host"
    networks:
      - webnet
networks:
      webnet: