version: '3'
services:
  web:
    # replace username/repo:tag with your name and image details
    image: shailensukul/getting-started:part2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
    networks:
      - webnet
  redis:
    image: redis
volumes:
  logvolume01: {}
networks:
  webnet: